#!/usr/bin/env python3
"""External training runtime for real SLM finetuning.

This script runs supervised finetuning using HuggingFace Trainer against
prepared JSONL datasets generated by this platform.
"""

from __future__ import annotations

import argparse
import inspect
import json
import traceback
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_DATA_DIR = REPO_ROOT / "data"


def utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run external SLM finetuning workflow")
    parser.add_argument("--project", type=int, required=True, help="Project ID")
    parser.add_argument("--experiment", type=int, required=True, help="Experiment ID")
    parser.add_argument("--output", type=str, required=True, help="Experiment output directory")
    parser.add_argument("--base-model", type=str, required=True, help="HF base model id/path")
    parser.add_argument("--config", type=str, default="", help="Path to training config JSON")
    parser.add_argument("--train-file", type=str, default="", help="Path to train JSONL file")
    parser.add_argument("--val-file", type=str, default="", help="Path to validation JSONL file")
    parser.add_argument("--data-dir", type=str, default=str(DEFAULT_DATA_DIR), help="Root data directory")
    parser.add_argument("--max-train-samples", type=int, default=0, help="Optional train row cap for dry runs")
    parser.add_argument("--max-eval-samples", type=int, default=0, help="Optional eval row cap for dry runs")
    parser.add_argument("--seed", type=int, default=42)
    return parser.parse_args()


def _load_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Training config must be a JSON object: {path}")
    return payload


def _resolve_dataset_paths(args: argparse.Namespace) -> tuple[Path, Path | None]:
    data_dir = Path(args.data_dir).expanduser().resolve()
    project_dir = data_dir / "projects" / str(args.project) / "prepared"
    train_file = (
        Path(args.train_file).expanduser().resolve()
        if args.train_file
        else project_dir / "train.jsonl"
    )
    val_file = (
        Path(args.val_file).expanduser().resolve()
        if args.val_file
        else project_dir / "val.jsonl"
    )
    if not train_file.exists():
        raise FileNotFoundError(
            f"Training dataset not found: {train_file}. "
            "Run dataset split before training."
        )
    return train_file, val_file if val_file.exists() else None


def _qa_to_chat_text(question: str, answer: str, template_name: str) -> str:
    q = question.strip()
    a = answer.strip()
    if not q or not a:
        return ""
    if template_name == "llama3":
        return (
            "<|start_header_id|>user<|end_header_id|>\n\n"
            f"{q}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"
            f"{a}<|eot_id|>"
        )
    if template_name == "chatml":
        return f"<|im_start|>user\n{q}<|im_end|>\n<|im_start|>assistant\n{a}<|im_end|>"
    if template_name == "zephyr":
        return f"<|user|>\n{q}</s>\n<|assistant|>\n{a}</s>"
    if template_name == "phi3":
        return f"<|user|>\n{q}<|end|>\n<|assistant|>\n{a}<|end|>"
    return f"User: {q}\nAssistant: {a}"


def _record_to_text(row: dict[str, Any], chat_template: str) -> str:
    direct_text = row.get("text") or row.get("content")
    if isinstance(direct_text, str) and direct_text.strip():
        return direct_text.strip()

    question = row.get("question") or row.get("prompt") or row.get("instruction")
    answer = row.get("answer") or row.get("completion") or row.get("output") or row.get("response")
    if isinstance(question, str) and isinstance(answer, str):
        rendered = _qa_to_chat_text(question, answer, chat_template)
        if rendered:
            return rendered

    if isinstance(question, str) and question.strip():
        optional_input = row.get("input")
        if isinstance(optional_input, str) and optional_input.strip():
            return f"Instruction: {question.strip()}\nInput: {optional_input.strip()}"
        return question.strip()

    return ""


def _last_metric_value(log_history: list[dict[str, Any]], key: str) -> float | None:
    for row in reversed(log_history):
        value = row.get(key)
        if isinstance(value, (int, float)):
            return float(value)
    return None


def _build_checkpoint_index(output_dir: Path, log_history: list[dict[str, Any]]) -> list[dict[str, Any]]:
    checkpoints: list[dict[str, Any]] = []
    checkpoint_dirs = sorted(
        [p for p in output_dir.glob("checkpoint-*") if p.is_dir()],
        key=lambda p: int(p.name.split("-", 1)[1]) if p.name.split("-", 1)[1].isdigit() else 0,
    )

    for ck_dir in checkpoint_dirs:
        suffix = ck_dir.name.split("-", 1)[1]
        if not suffix.isdigit():
            continue
        step = int(suffix)
        epoch = None
        train_loss = None
        eval_loss = None
        for row in reversed(log_history):
            row_step = row.get("step")
            if not isinstance(row_step, (int, float)):
                continue
            if int(row_step) > step:
                continue
            if epoch is None and isinstance(row.get("epoch"), (int, float)):
                epoch = int(row["epoch"]) if row["epoch"] else 1
            if train_loss is None and isinstance(row.get("loss"), (int, float)):
                train_loss = float(row["loss"])
            if eval_loss is None and isinstance(row.get("eval_loss"), (int, float)):
                eval_loss = float(row["eval_loss"])
            if epoch is not None and train_loss is not None and eval_loss is not None:
                break
        checkpoints.append(
            {
                "step": step,
                "epoch": epoch or 1,
                "train_loss": train_loss,
                "eval_loss": eval_loss,
                "file_path": str(ck_dir),
                "is_best": False,
            }
        )

    best_eval = None
    best_idx = None
    for idx, ck in enumerate(checkpoints):
        loss = ck.get("eval_loss")
        if isinstance(loss, (int, float)):
            if best_eval is None or float(loss) < best_eval:
                best_eval = float(loss)
                best_idx = idx
    if best_idx is not None:
        checkpoints[best_idx]["is_best"] = True

    return checkpoints


def _coerce_training_arguments_kwargs(
    kwargs: dict[str, Any],
    training_args_cls: type,
) -> tuple[dict[str, Any], list[str]]:
    """
    Make TrainingArguments kwargs robust across transformers major versions.

    transformers v5 renamed some fields (for example `evaluation_strategy` -> `eval_strategy`)
    and removed others (for example `overwrite_output_dir`). We map known aliases and drop
    unsupported keys with a warning so the runtime remains backward compatible.
    """
    accepted = inspect.signature(training_args_cls.__init__).parameters
    normalized = dict(kwargs)

    alias_pairs = [
        ("evaluation_strategy", "eval_strategy"),
        ("eval_strategy", "evaluation_strategy"),
    ]
    for old_name, new_name in alias_pairs:
        if old_name in normalized and old_name not in accepted and new_name in accepted:
            normalized[new_name] = normalized.pop(old_name)

    filtered: dict[str, Any] = {}
    dropped: list[str] = []
    for key, value in normalized.items():
        if key in accepted:
            filtered[key] = value
        else:
            dropped.append(key)

    return filtered, sorted(dropped)


def _coerce_trainer_kwargs(
    kwargs: dict[str, Any],
    trainer_cls: type,
) -> tuple[dict[str, Any], list[str]]:
    """
    Make Trainer kwargs robust across transformers major versions.

    transformers v5 replaced `tokenizer` with `processing_class`.
    We map known aliases and drop unsupported keys.
    """
    accepted = inspect.signature(trainer_cls.__init__).parameters
    normalized = dict(kwargs)

    alias_pairs = [
        ("tokenizer", "processing_class"),
        ("processing_class", "tokenizer"),
    ]
    for old_name, new_name in alias_pairs:
        if old_name in normalized and old_name not in accepted and new_name in accepted:
            normalized[new_name] = normalized.pop(old_name)

    filtered: dict[str, Any] = {}
    dropped: list[str] = []
    for key, value in normalized.items():
        if key in accepted:
            filtered[key] = value
        else:
            dropped.append(key)

    return filtered, sorted(dropped)


def run_training(args: argparse.Namespace) -> dict[str, Any]:
    started_at = utcnow()
    output_dir = Path(args.output).expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)
    model_dir = output_dir / "model"
    config_path = Path(args.config).expanduser().resolve() if args.config else output_dir / "training_config.json"
    train_file, val_file = _resolve_dataset_paths(args)

    config = _load_json(config_path)
    chat_template = str(config.get("chat_template", "llama3"))
    max_seq_length = int(config.get("max_seq_length", 2048))
    batch_size = int(config.get("batch_size", 4))
    grad_accum = int(config.get("gradient_accumulation_steps", 4))
    learning_rate = float(config.get("learning_rate", 2e-4))
    num_epochs = float(config.get("num_epochs", 3))
    weight_decay = float(config.get("weight_decay", 0.01))
    warmup_ratio = float(config.get("warmup_ratio", 0.03))
    save_steps = int(config.get("save_steps", 100))
    eval_steps = int(config.get("eval_steps", 100))
    lr_scheduler = str(config.get("lr_scheduler", "cosine"))
    optimizer = str(config.get("optimizer", "adamw_torch"))
    seed = int(config.get("seed", args.seed))
    use_lora = bool(config.get("use_lora", False))
    lora_r = int(config.get("lora_r", 16))
    lora_alpha = int(config.get("lora_alpha", 32))
    lora_dropout = float(config.get("lora_dropout", 0.05))
    target_modules = config.get("target_modules", ["q_proj", "v_proj"])
    gradient_checkpointing = bool(config.get("gradient_checkpointing", True))
    want_flash_attention = bool(config.get("flash_attention", True))
    want_fp16 = bool(config.get("fp16", False))
    want_bf16 = bool(config.get("bf16", True))
    max_train_samples = args.max_train_samples
    max_eval_samples = args.max_eval_samples

    try:
        import torch
        import transformers as hf_transformers
        from datasets import load_dataset
        from transformers import (
            AutoModelForCausalLM,
            AutoTokenizer,
            DataCollatorForLanguageModeling,
            Trainer,
            TrainingArguments,
            set_seed,
        )
    except ImportError as e:
        raise RuntimeError(
            "Missing training dependencies. Install torch, datasets, transformers, and accelerate."
        ) from e

    warnings: list[str] = []
    set_seed(seed)

    # Load JSONL datasets.
    data_files: dict[str, str] = {"train": str(train_file)}
    if val_file is not None:
        data_files["validation"] = str(val_file)
    raw_ds = load_dataset("json", data_files=data_files)

    train_ds = raw_ds["train"]
    eval_ds = raw_ds["validation"] if "validation" in raw_ds else None
    if max_train_samples > 0:
        train_ds = train_ds.select(range(min(len(train_ds), max_train_samples)))
    if eval_ds is not None and max_eval_samples > 0:
        eval_ds = eval_ds.select(range(min(len(eval_ds), max_eval_samples)))

    # Convert heterogeneous records into text-formatted SFT samples.
    def to_text_record(row: dict[str, Any]) -> dict[str, str]:
        text = _record_to_text(row, chat_template)
        return {"text": text}

    train_text = train_ds.map(to_text_record, remove_columns=train_ds.column_names)
    train_text = train_text.filter(lambda row: bool(row.get("text", "").strip()))
    if len(train_text) == 0:
        raise ValueError("No valid training rows after normalization to text format.")

    eval_text = None
    if eval_ds is not None:
        eval_text = eval_ds.map(to_text_record, remove_columns=eval_ds.column_names)
        eval_text = eval_text.filter(lambda row: bool(row.get("text", "").strip()))
        if len(eval_text) == 0:
            eval_text = None

    tokenizer = AutoTokenizer.from_pretrained(args.base_model, trust_remote_code=True)
    if tokenizer.pad_token is None:
        if tokenizer.eos_token:
            tokenizer.pad_token = tokenizer.eos_token
        else:
            tokenizer.add_special_tokens({"pad_token": "<|pad|>"})

    model_kwargs: dict[str, Any] = {"trust_remote_code": True}
    use_cuda = torch.cuda.is_available()
    use_bf16 = bool(use_cuda and want_bf16 and torch.cuda.is_bf16_supported())
    use_fp16 = bool(use_cuda and not use_bf16 and want_fp16)
    if use_bf16:
        model_kwargs["torch_dtype"] = torch.bfloat16
    elif use_fp16:
        model_kwargs["torch_dtype"] = torch.float16

    if want_flash_attention and use_cuda:
        model_kwargs["attn_implementation"] = "flash_attention_2"

    try:
        model = AutoModelForCausalLM.from_pretrained(args.base_model, **model_kwargs)
    except Exception as e:
        if model_kwargs.get("attn_implementation") == "flash_attention_2":
            warnings.append(f"flash_attention_2 unavailable; falling back. Details: {e}")
            model_kwargs.pop("attn_implementation", None)
            model = AutoModelForCausalLM.from_pretrained(args.base_model, **model_kwargs)
        else:
            raise

    if model.config.pad_token_id is None:
        model.config.pad_token_id = tokenizer.pad_token_id
    if len(tokenizer) > model.get_input_embeddings().num_embeddings:
        model.resize_token_embeddings(len(tokenizer))
    if gradient_checkpointing:
        model.gradient_checkpointing_enable()
        model.config.use_cache = False

    if use_lora:
        try:
            from peft import LoraConfig, TaskType, get_peft_model
        except ImportError as e:
            raise RuntimeError(
                "LoRA training requested but peft is not installed. Install peft or set use_lora=false."
            ) from e

        if not isinstance(target_modules, list) or not target_modules:
            raise ValueError("target_modules must be a non-empty list when use_lora=true")
        model = get_peft_model(
            model,
            LoraConfig(
                task_type=TaskType.CAUSAL_LM,
                r=lora_r,
                lora_alpha=lora_alpha,
                lora_dropout=lora_dropout,
                target_modules=target_modules,
                bias="none",
            ),
        )

    def tokenize_rows(rows: dict[str, list[str]]) -> dict[str, Any]:
        return tokenizer(
            rows["text"],
            truncation=True,
            max_length=max_seq_length,
            padding=False,
        )

    tokenized_train = train_text.map(tokenize_rows, batched=True, remove_columns=train_text.column_names)
    tokenized_eval = (
        eval_text.map(tokenize_rows, batched=True, remove_columns=eval_text.column_names)
        if eval_text is not None
        else None
    )
    has_eval = tokenized_eval is not None and len(tokenized_eval) > 0

    if optimizer == "paged_adamw_8bit":
        try:
            import bitsandbytes  # noqa: F401
        except ImportError:
            warnings.append("bitsandbytes not installed; using adamw_torch instead of paged_adamw_8bit.")
            optimizer = "adamw_torch"

    args_kwargs: dict[str, Any] = {
        "output_dir": str(output_dir),
        "overwrite_output_dir": True,
        "num_train_epochs": num_epochs,
        "per_device_train_batch_size": batch_size,
        "gradient_accumulation_steps": grad_accum,
        "learning_rate": learning_rate,
        "weight_decay": weight_decay,
        "warmup_ratio": warmup_ratio,
        "lr_scheduler_type": lr_scheduler,
        "logging_steps": max(1, min(save_steps, 20)),
        "save_strategy": "steps",
        "save_steps": max(1, save_steps),
        "save_total_limit": 3,
        "optim": optimizer,
        "gradient_checkpointing": gradient_checkpointing,
        "report_to": [],
        "seed": seed,
        "data_seed": seed,
        "dataloader_num_workers": 0,
        "remove_unused_columns": True,
        "fp16": use_fp16,
        "bf16": use_bf16,
    }
    if has_eval:
        args_kwargs["evaluation_strategy"] = "steps"
        args_kwargs["eval_steps"] = max(1, eval_steps)
        args_kwargs["load_best_model_at_end"] = True
        args_kwargs["metric_for_best_model"] = "eval_loss"
        args_kwargs["greater_is_better"] = False
        args_kwargs["per_device_eval_batch_size"] = batch_size
    else:
        args_kwargs["evaluation_strategy"] = "no"

    safe_args_kwargs, dropped_arg_keys = _coerce_training_arguments_kwargs(args_kwargs, TrainingArguments)
    if dropped_arg_keys:
        warnings.append(
            "Ignoring unsupported TrainingArguments keys "
            f"for transformers {hf_transformers.__version__}: {', '.join(dropped_arg_keys)}."
        )

    training_args = TrainingArguments(**safe_args_kwargs)
    trainer_kwargs: dict[str, Any] = {
        "model": model,
        "args": training_args,
        "train_dataset": tokenized_train,
        "eval_dataset": tokenized_eval if has_eval else None,
        "tokenizer": tokenizer,
        "data_collator": DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
    }
    safe_trainer_kwargs, dropped_trainer_keys = _coerce_trainer_kwargs(trainer_kwargs, Trainer)
    if dropped_trainer_keys:
        warnings.append(
            "Ignoring unsupported Trainer keys "
            f"for transformers {hf_transformers.__version__}: {', '.join(dropped_trainer_keys)}."
        )

    trainer = Trainer(**safe_trainer_kwargs)

    train_result = trainer.train()
    eval_metrics = trainer.evaluate() if has_eval else {}

    trainer.save_model(str(model_dir))
    tokenizer.save_pretrained(str(model_dir))

    log_history = [row for row in trainer.state.log_history if isinstance(row, dict)]
    metrics_path = output_dir / "metrics.jsonl"
    with open(metrics_path, "w", encoding="utf-8") as f:
        for row in log_history:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    checkpoints = _build_checkpoint_index(output_dir, log_history)
    final_train_loss = _last_metric_value(log_history, "loss")
    final_eval_loss = _last_metric_value(log_history, "eval_loss")
    best_eval_loss = None
    if checkpoints:
        eval_losses = [ck["eval_loss"] for ck in checkpoints if isinstance(ck.get("eval_loss"), (int, float))]
        if eval_losses:
            best_eval_loss = float(min(eval_losses))

    finished_at = utcnow()
    report = {
        "project_id": args.project,
        "experiment_id": args.experiment,
        "backend": "hf_trainer",
        "base_model": args.base_model,
        "started_at": started_at,
        "finished_at": finished_at,
        "config_path": str(config_path),
        "train_file": str(train_file),
        "val_file": str(val_file) if val_file is not None else None,
        "model_dir": str(model_dir),
        "metrics_path": str(metrics_path),
        "epochs": num_epochs,
        "total_steps": int(trainer.state.global_step),
        "train_records": len(train_text),
        "eval_records": len(eval_text) if eval_text is not None else 0,
        "final_train_loss": final_train_loss,
        "final_eval_loss": final_eval_loss or eval_metrics.get("eval_loss"),
        "best_eval_loss": best_eval_loss,
        "checkpoints": checkpoints,
        "train_runtime_seconds": train_result.metrics.get("train_runtime"),
        "warnings": warnings,
    }
    (output_dir / "training_report.json").write_text(
        json.dumps(report, indent=2),
        encoding="utf-8",
    )
    return report


def main() -> int:
    args = parse_args()
    try:
        report = run_training(args)
        print(json.dumps({"status": "completed", "report": report}))
        return 0
    except Exception as e:
        traceback.print_exc()
        print(json.dumps({"status": "failed", "error": str(e)}))
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
