#!/usr/bin/env python3
"""Generate full ``brewslm --help`` reference Markdown.

For each top-level subcommand we run ``brewslm <cmd> --help`` and, when
the subcommand has its own subparsers, also ``brewslm <cmd> <sub> --help``.
The output of each is wrapped in a fenced code block under its own
heading. Designed to be re-run safely — the output file is overwritten.

Usage:

  cd slm-docs
  python scripts/generate_cli_ref.py \
    --cli /path/to/backend/scripts/brewslm.py \
    --out docs/reference/cli-full.md

If ``--cli`` isn't passed we look for ``backend/scripts/brewslm.py``
relative to the repo root.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


HEADER_NOTE = (
    "<!-- Auto-generated by slm-docs/scripts/generate_cli_ref.py. "
    "Do not edit by hand — re-run the generator instead. -->"
)


def _resolve_cli_path(cli_arg: str | None) -> Path:
    if cli_arg:
        return Path(cli_arg).expanduser().resolve()
    repo_root = Path(__file__).resolve().parent.parent.parent
    candidate = repo_root / "backend" / "scripts" / "brewslm.py"
    if not candidate.exists():
        raise FileNotFoundError(
            f"Could not find brewslm.py at {candidate}. Pass --cli explicitly."
        )
    return candidate


def _run_help(cli_path: Path, parts: list[str]) -> str:
    env = os.environ.copy()
    env.setdefault("PYTHONPATH", str(cli_path.parent.parent))
    # Wide help output for tables; falls back to default if not honoured.
    env.setdefault("COLUMNS", "120")
    try:
        result = subprocess.run(
            [sys.executable, str(cli_path), *parts, "--help"],
            capture_output=True,
            text=True,
            check=False,
            timeout=15,
            env=env,
        )
    except subprocess.TimeoutExpired:
        return f"(help timed out for: {' '.join(parts)})"
    out = (result.stdout or "") + (result.stderr or "")
    return out.rstrip() + "\n"


SUBCOMMAND_LINE = re.compile(r"^\s{2,}([a-z][a-z0-9_-]*)(?:\s+|$)")


def _extract_subcommands(help_text: str) -> list[str]:
    """Parse argparse subparsers section out of help text."""

    lines = help_text.splitlines()
    inside_subparser_block = False
    seen: list[str] = []
    seen_set: set[str] = set()
    for line in lines:
        # argparse renders subparser names indented under "positional arguments"
        # / "subcommands" — match indented identifier-leading lines.
        # Conservative: only enter the block after we see a "{a,b,c}" line.
        if re.match(r"^\s+\{[a-z0-9,_-]+\}\s*$", line):
            inside_subparser_block = True
            continue
        if not inside_subparser_block:
            continue
        if not line.strip():
            inside_subparser_block = False
            continue
        match = SUBCOMMAND_LINE.match(line)
        if not match:
            inside_subparser_block = False
            continue
        token = match.group(1)
        # Filter out flag-ish tokens that snuck in.
        if token.startswith("-"):
            continue
        if token in seen_set:
            continue
        seen.append(token)
        seen_set.add(token)
    return seen


def _slugify(value: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-") or "cmd"


def _render(cli_path: Path) -> str:
    top_help = _run_help(cli_path, [])
    top_subs = _extract_subcommands(top_help)

    chunks: list[str] = []
    chunks.append("---")
    chunks.append("sidebar_position: 5")
    chunks.append("title: CLI full reference")
    chunks.append("---")
    chunks.append("")
    chunks.append(HEADER_NOTE)
    chunks.append("")
    chunks.append("# CLI full reference")
    chunks.append("")
    chunks.append(
        "Auto-generated from `brewslm --help`. For curated examples and "
        "the trio (UI / CLI / API) format see [CLI reference](cli.md)."
    )
    chunks.append("")
    chunks.append("## `brewslm`")
    chunks.append("")
    chunks.append("```text")
    chunks.append(top_help.rstrip())
    chunks.append("```")
    chunks.append("")

    for sub in top_subs:
        sub_help = _run_help(cli_path, [sub])
        anchor = _slugify(sub)
        chunks.append(f"## `brewslm {sub}`  {{#cmd-{anchor}}}")
        chunks.append("")
        chunks.append("```text")
        chunks.append(sub_help.rstrip())
        chunks.append("```")
        chunks.append("")

        # Recurse one level into nested subparsers.
        for nested in _extract_subcommands(sub_help):
            nested_help = _run_help(cli_path, [sub, nested])
            nested_anchor = _slugify(f"{sub}-{nested}")
            chunks.append(f"### `brewslm {sub} {nested}`  {{#cmd-{nested_anchor}}}")
            chunks.append("")
            chunks.append("```text")
            chunks.append(nested_help.rstrip())
            chunks.append("```")
            chunks.append("")

    return "\n".join(chunks).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--cli",
        default=None,
        help="Path to brewslm.py. Defaults to ../backend/scripts/brewslm.py.",
    )
    parser.add_argument(
        "--out",
        default="docs/reference/cli-full.md",
        help="Output Markdown file (relative to slm-docs/).",
    )
    args = parser.parse_args()

    cli_path = _resolve_cli_path(args.cli)
    out_path = (Path(__file__).resolve().parent.parent / args.out).resolve()
    out_path.parent.mkdir(parents=True, exist_ok=True)

    payload = _render(cli_path)
    out_path.write_text(payload, encoding="utf-8")
    print(f"Wrote {len(payload):,} bytes to {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
