#!/usr/bin/env python3
"""Generate per-tag API reference Markdown from a FastAPI OpenAPI spec.

Pipeline:

  cd backend
  PYTHONPATH=. python scripts/dump_openapi.py --out ../slm-docs/openapi.json

  cd ../slm-docs
  python scripts/generate_api_ref.py --spec openapi.json

Produces one Markdown file per OpenAPI tag under
``docs/reference/api/``, plus an index page at
``docs/reference/api/index.md``. Designed to be re-run safely — the
output directory is wiped (only its .md files) before each run.

The generator is deliberately conservative: it doesn't try to be a
prettier-than-Swagger UI. It produces a flat, greppable, code-review
friendly Markdown surface so a developer can ctrl-F an endpoint or
property without leaving the docs site.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from pathlib import Path
from typing import Any


METHOD_ORDER = ["get", "post", "put", "patch", "delete", "head", "options"]
DEFAULT_TAG = "Misc"
HEADER_NOTE = (
    "<!-- Auto-generated by slm-docs/scripts/generate_api_ref.py. "
    "Do not edit by hand — re-run the generator instead. -->"
)


def _slugify(value: str) -> str:
    token = re.sub(r"[^a-z0-9]+", "-", value.lower())
    return token.strip("-") or "untagged"


def _markdown_safe(value: str) -> str:
    """Escape characters that confuse MDX inside a table cell.

    MDX 3 parses bare ``<`` / ``>`` as JSX delimiters even inside table
    cells, so anything carrying ``>=`` / ``<=`` / generic-looking
    ``<Foo>`` text breaks the build. HTML-entity escape both, and also
    escape pipes so they don't end the cell.
    """

    return (
        value.replace("|", "\\|")
        .replace("\r", "")
        .replace("\n", " ")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _resolve_ref(ref: str, components: dict[str, Any]) -> dict[str, Any]:
    """Resolve a JSON-pointer-style $ref into the components dict."""

    # ref format: #/components/schemas/Foo
    parts = ref.lstrip("#/").split("/")
    node: Any = {"components": components}
    for part in parts:
        if not isinstance(node, dict):
            return {}
        node = node.get(part, {})
    return node if isinstance(node, dict) else {}


def _type_repr(schema: dict[str, Any]) -> str:
    """Render a schema as a compact type string."""

    if not schema:
        return "any"

    if "$ref" in schema:
        name = schema["$ref"].rsplit("/", 1)[-1]
        return name

    any_of = schema.get("anyOf") or schema.get("oneOf")
    if any_of:
        parts = [_type_repr(s) for s in any_of]
        return " \\| ".join(parts)

    if "enum" in schema:
        values = ", ".join(json.dumps(v) for v in schema["enum"])
        return f"enum({values})"

    schema_type = schema.get("type")
    if schema_type == "array":
        items = _type_repr(schema.get("items", {}))
        return f"{items}[]"
    if schema_type == "object":
        return "object"
    if schema_type:
        fmt = schema.get("format")
        return f"{schema_type}({fmt})" if fmt else schema_type
    return "any"


def _flatten_schema(
    schema: dict[str, Any],
    components: dict[str, Any],
    depth: int = 0,
    seen: set[str] | None = None,
) -> list[tuple[str, str, bool, str]]:
    """Flatten an object schema into (path, type, required, description) rows.

    Recursion is capped at depth 3 and skips already-seen refs so we
    don't spin out on circular models.
    """

    if seen is None:
        seen = set()

    if "$ref" in schema:
        ref = schema["$ref"]
        if ref in seen or depth > 3:
            return [("", _type_repr(schema), False, "")]
        seen.add(ref)
        return _flatten_schema(_resolve_ref(ref, components), components, depth, seen)

    rows: list[tuple[str, str, bool, str]] = []
    schema_type = schema.get("type")
    required = set(schema.get("required") or [])
    properties = schema.get("properties") or {}

    if schema_type == "object" or properties:
        for name, child in properties.items():
            child_type = _type_repr(child)
            description = child.get("description", "")
            rows.append((name, child_type, name in required, description))
        return rows

    return [("", _type_repr(schema), False, schema.get("description", ""))]


def _format_body_schema(
    request_body: dict[str, Any] | None,
    components: dict[str, Any],
) -> str:
    if not request_body:
        return ""

    content = request_body.get("content") or {}
    block_parts: list[str] = []
    required = request_body.get("required", False)
    block_parts.append("**Request body**" + (" (required)" if required else " (optional)"))

    for content_type, content_payload in content.items():
        schema = content_payload.get("schema") or {}
        type_str = _type_repr(schema)
        rows = _flatten_schema(schema, components)
        block_parts.append(f"\nContent type: `{content_type}` — `{type_str}`")
        if rows and rows[0][0]:
            block_parts.append("")
            block_parts.append("| Field | Type | Required | Description |")
            block_parts.append("|---|---|---|---|")
            for name, type_repr, is_req, desc in rows:
                block_parts.append(
                    "| `{}` | `{}` | {} | {} |".format(
                        _markdown_safe(name),
                        _markdown_safe(type_repr),
                        "yes" if is_req else "no",
                        _markdown_safe(desc),
                    )
                )

    return "\n".join(block_parts)


def _format_responses(
    responses: dict[str, Any] | None,
    components: dict[str, Any],
) -> str:
    if not responses:
        return ""

    lines = ["**Responses**", "", "| Status | Schema | Description |", "|---|---|---|"]
    for status, payload in responses.items():
        description = payload.get("description") or ""
        content = payload.get("content") or {}
        if content:
            primary = next(iter(content.values()))
            schema = primary.get("schema") or {}
            schema_str = _type_repr(schema)
        else:
            schema_str = "—"
        lines.append(
            "| `{}` | `{}` | {} |".format(
                _markdown_safe(status),
                _markdown_safe(schema_str),
                _markdown_safe(description),
            )
        )
    return "\n".join(lines)


def _format_parameters(parameters: list[dict[str, Any]] | None) -> str:
    if not parameters:
        return ""

    lines = ["**Parameters**", "", "| Name | In | Type | Required | Description |", "|---|---|---|---|---|"]
    for param in parameters:
        schema = param.get("schema") or {}
        type_str = _type_repr(schema)
        lines.append(
            "| `{}` | `{}` | `{}` | {} | {} |".format(
                _markdown_safe(str(param.get("name", ""))),
                _markdown_safe(str(param.get("in", ""))),
                _markdown_safe(type_str),
                "yes" if param.get("required") else "no",
                _markdown_safe(param.get("description", "")),
            )
        )
    return "\n".join(lines)


def _render_endpoint(
    method: str,
    path: str,
    op: dict[str, Any],
    components: dict[str, Any],
) -> str:
    summary = op.get("summary") or op.get("operationId") or path
    description = op.get("description") or ""

    sections: list[str] = []
    sections.append(f"### `{method.upper()} {path}`")
    sections.append("")
    sections.append(f"**{summary}**")
    if description:
        sections.append("")
        sections.append(description.strip())

    params_block = _format_parameters(op.get("parameters"))
    if params_block:
        sections.append("")
        sections.append(params_block)

    body_block = _format_body_schema(op.get("requestBody"), components)
    if body_block:
        sections.append("")
        sections.append(body_block)

    response_block = _format_responses(op.get("responses"), components)
    if response_block:
        sections.append("")
        sections.append(response_block)

    return "\n".join(sections) + "\n"


def _collect_endpoints_by_tag(spec: dict[str, Any]) -> dict[str, list[tuple[str, str, dict[str, Any]]]]:
    paths = spec.get("paths") or {}
    by_tag: dict[str, list[tuple[str, str, dict[str, Any]]]] = defaultdict(list)
    for path, path_item in paths.items():
        if not isinstance(path_item, dict):
            continue
        for method, op in path_item.items():
            if method.lower() not in METHOD_ORDER:
                continue
            if not isinstance(op, dict):
                continue
            tags = op.get("tags") or [DEFAULT_TAG]
            for tag in tags:
                by_tag[tag].append((method.lower(), path, op))
    return by_tag


def _sort_endpoints(endpoints: list[tuple[str, str, dict[str, Any]]]) -> list[tuple[str, str, dict[str, Any]]]:
    def key(entry: tuple[str, str, dict[str, Any]]) -> tuple[int, str, int]:
        method, path, _ = entry
        method_rank = METHOD_ORDER.index(method) if method in METHOD_ORDER else len(METHOD_ORDER)
        return (path.count("/"), path, method_rank)

    return sorted(endpoints, key=key)


def _render_tag_page(
    tag: str,
    endpoints: list[tuple[str, str, dict[str, Any]]],
    components: dict[str, Any],
    sidebar_position: int,
) -> str:
    lines = [
        "---",
        f"sidebar_position: {sidebar_position}",
        f"title: {tag}",
        "---",
        "",
        HEADER_NOTE,
        "",
        f"# {tag}",
        "",
        f"Auto-generated reference for the **{tag}** API. {len(endpoints)} endpoint(s).",
        "",
        "For curated narrative + UI / CLI walkthroughs see the corresponding section under",
        "[Pipeline workflows](../../workflows/pipeline-overview.md), [Deployment](../../deployment/plan.md),",
        "[Observability](../../observability/run-events.md), or [Extensions](../../extensions/contracts.md).",
        "",
    ]
    for method, path, op in _sort_endpoints(endpoints):
        lines.append(_render_endpoint(method, path, op, components))
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _render_index(
    tags: list[tuple[str, int]],
    total_endpoints: int,
    info: dict[str, Any],
) -> str:
    lines = [
        "---",
        "sidebar_position: 1",
        "title: Auto API index",
        "---",
        "",
        HEADER_NOTE,
        "",
        "# Auto-generated API reference",
        "",
        f"**{info.get('title', 'BrewSLM API')}** — version `{info.get('version', '?')}`. "
        f"{total_endpoints} endpoint(s) across {len(tags)} tag(s).",
        "",
        "This section is auto-generated from the FastAPI OpenAPI spec. For curated narrative",
        "+ UI / CLI walkthroughs see the linked workflow pages. The live Swagger UI is at",
        "`http://localhost:8000/api/docs`.",
        "",
        "## Tags",
        "",
        "| Tag | Endpoints |",
        "|---|---|",
    ]
    for tag, count in tags:
        slug = _slugify(tag)
        lines.append(f"| [{tag}]({slug}.md) | {count} |")

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--spec",
        required=True,
        help="Path to the OpenAPI JSON spec dumped by backend/scripts/dump_openapi.py.",
    )
    parser.add_argument(
        "--out",
        default="docs/reference/api",
        help="Output directory (relative to slm-docs/). Defaults to docs/reference/api.",
    )
    args = parser.parse_args()

    spec_path = Path(args.spec).resolve()
    if not spec_path.exists():
        print(f"Spec file not found: {spec_path}", flush=True)
        return 1
    spec = json.loads(spec_path.read_text(encoding="utf-8"))

    components = (spec.get("components") or {})
    by_tag = _collect_endpoints_by_tag(spec)

    out_dir = (Path(__file__).resolve().parent.parent / args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    # Wipe stale generated files (keep nothing else in this dir).
    for existing in out_dir.glob("*.md"):
        existing.unlink()

    tags_sorted = sorted(by_tag.items(), key=lambda kv: kv[0].lower())
    total = sum(len(v) for _, v in tags_sorted)

    index_payload = _render_index(
        [(tag, len(endpoints)) for tag, endpoints in tags_sorted],
        total_endpoints=total,
        info=spec.get("info") or {},
    )
    (out_dir / "index.md").write_text(index_payload, encoding="utf-8")

    for position, (tag, endpoints) in enumerate(tags_sorted, start=2):
        slug = _slugify(tag)
        payload = _render_tag_page(tag, endpoints, components, position)
        (out_dir / f"{slug}.md").write_text(payload, encoding="utf-8")
        print(f"  {slug}.md ({len(endpoints)} endpoints)")

    print(f"Wrote {len(tags_sorted) + 1} files to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
