#!/usr/bin/env python3
"""Regenerate INDEX.md — one-liner per backend/frontend module.

The output is consumed by AI coding agents (Claude Code, Codex) on
session start to skip the cost of grepping for "where is X". A
running ``CLAUDE.md`` + this generated ``INDEX.md`` together
replace ~5-10 tool calls per session.

Format per entry:

    <path>
      <one-line description from the file's docstring / header comment>

Files without a docstring/header are listed without a description
(intentional — the missing summary is a signal to fix the file).

Usage:
    python scripts/regenerate_index.py            # writes INDEX.md
    python scripts/regenerate_index.py --check    # exits 1 if stale
    python scripts/regenerate_index.py --stdout   # print, don't write

Wire as a pre-commit hook if you want it auto-enforced; see
``.git/hooks/pre-commit`` example at the bottom of this file.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path


# ─────────────────────────────────────────────────────────────────────
# Configuration
# ─────────────────────────────────────────────────────────────────────


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "INDEX.md"

# Section: (header, root_relative_glob, file_suffix_filter)
# Order matters — sections render in the order declared.
SECTIONS: list[tuple[str, str, tuple[str, ...]]] = [
    ("Backend · API routes", "backend/app/api", (".py",)),
    ("Backend · Services (business logic)", "backend/app/services", (".py",)),
    ("Backend · ORM models", "backend/app/models", (".py",)),
    ("Backend · Pydantic schemas", "backend/app/schemas", (".py",)),
    ("Backend · CLI scripts", "backend/scripts", (".py",)),
    ("Backend · Alembic migrations", "backend/alembic/versions", (".py",)),
    ("Frontend · API clients", "frontend/src/api", (".ts",)),
    ("Frontend · Zustand stores", "frontend/src/stores", (".ts",)),
    ("Frontend · Pages", "frontend/src/pages", (".tsx",)),
    ("Frontend · Components (by domain)", "frontend/src/components", (".tsx",)),
    ("Repo · Top-level scripts", "scripts", (".py", ".sh")),
]

# Files to skip entirely (noise / generated).
SKIP_NAMES = {"__init__.py", "__pycache__"}
SKIP_SUFFIXES = (".test.tsx", ".test.ts", ".test.py", ".test.tsx.snap")

# Headers that survive in the script's own output — guards us against
# silent failures where the script emits something but the body is empty.
PREAMBLE = """# BrewSLM — Module Index

Auto-generated by `scripts/regenerate_index.py`. One line per source
file, drawn from the first sentence of the file's docstring (Python)
or header `/** ... */` block (TypeScript). Re-run after structural
changes:

```
python scripts/regenerate_index.py
```

A missing description is a signal that the file should grow a one-
line docstring at the top.

See [CLAUDE.md](./CLAUDE.md) for conventions, stack details, and
session-start guidance.

"""


# ─────────────────────────────────────────────────────────────────────
# Docstring / header extraction
# ─────────────────────────────────────────────────────────────────────


# Catastrophic-backtracking-prone patterns avoided — extraction is
# done line-by-line below instead of via multi-line regex. The one
# regex we keep is the shebang-stripper for shell scripts.

_SHELL_FIRST_COMMENT_RE = re.compile(
    r'^(?:#!.*\n)?(?:\s*\n)*#\s*(?P<body>.+)',
)


@dataclass
class FileSummary:
    rel_path: str   # repo-relative, forward slashes
    summary: str    # one line; empty when missing


def _first_meaningful_line(text: str) -> str:
    """First non-empty stripped line of a docstring/comment body. Trims
    quotes, leading asterisks (TS block-comment formatting), and trailing
    punctuation that would collide with our '— ' separator."""
    for raw in text.splitlines():
        line = raw.strip()
        # Strip TS block-comment leading asterisk.
        if line.startswith("*"):
            line = line[1:].strip()
        # Drop empty / divider lines.
        if not line:
            continue
        if line.startswith("=") or line.startswith("-"):
            # Probably a separator like "==========" — skip.
            continue
        return line
    return ""


def _extract_python_summary(text: str) -> str:
    """Walk leading comments / blank lines / ``from __future__`` imports
    and return the first line of the next triple-quoted block, if any.
    Linear-time line scan — avoids the catastrophic-backtracking trap
    that a single regex would hit on files without a docstring."""
    lines = text.splitlines()
    idx = 0
    while idx < len(lines):
        stripped = lines[idx].strip()
        if not stripped:
            idx += 1
            continue
        if stripped.startswith("#"):
            idx += 1
            continue
        if stripped.startswith("from __future__"):
            idx += 1
            continue
        break
    if idx >= len(lines):
        return ""
    first = lines[idx].lstrip()
    for opener in ('"""', "'''"):
        if first.startswith(opener):
            after = first[len(opener):]
            # Single-line """text""" form.
            if opener in after:
                return _first_meaningful_line(after.split(opener, 1)[0])
            # Multi-line — gather until the closing triple quote.
            body_lines = [after] if after else []
            for follow in lines[idx + 1:]:
                if opener in follow:
                    body_lines.append(follow.split(opener, 1)[0])
                    break
                body_lines.append(follow)
            return _first_meaningful_line("\n".join(body_lines))
    return ""


def _extract_typescript_summary(text: str) -> str:
    """Prefer the first ``/** ... */`` block-comment at the top of the
    file; fall back to consecutive ``// ...`` line comments. Both done
    via line scan to avoid regex backtracking."""
    lines = text.splitlines()
    if not lines:
        return ""
    # Skip leading blanks.
    idx = 0
    while idx < len(lines) and not lines[idx].strip():
        idx += 1
    if idx >= len(lines):
        return ""
    first = lines[idx].lstrip()
    # Block-comment header.
    if first.startswith("/**") or first.startswith("/*"):
        opener_len = 3 if first.startswith("/**") else 2
        after = first[opener_len:]
        if "*/" in after:
            return _first_meaningful_line(after.split("*/", 1)[0])
        body_lines = [after] if after else []
        for follow in lines[idx + 1:]:
            if "*/" in follow:
                body_lines.append(follow.split("*/", 1)[0])
                break
            body_lines.append(follow)
        return _first_meaningful_line("\n".join(body_lines))
    # Line-comment header.
    if first.startswith("//"):
        return first.lstrip("/").strip()
    return ""


def _extract_shell_summary(text: str) -> str:
    match = _SHELL_FIRST_COMMENT_RE.match(text)
    return match.group("body").strip() if match else ""


def extract_summary(path: Path) -> str:
    """Return the first-line summary for a file, or '' when none."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""
    suffix = path.suffix.lower()
    if suffix == ".py":
        return _extract_python_summary(text)
    if suffix in (".ts", ".tsx"):
        return _extract_typescript_summary(text)
    if suffix == ".sh":
        return _extract_shell_summary(text)
    return ""


# ─────────────────────────────────────────────────────────────────────
# Section assembly
# ─────────────────────────────────────────────────────────────────────


def _should_skip(path: Path) -> bool:
    if path.name in SKIP_NAMES:
        return True
    if any(path.name.endswith(suffix) for suffix in SKIP_SUFFIXES):
        return True
    if "__pycache__" in path.parts:
        return True
    return False


def collect_section(root_glob: str, suffixes: tuple[str, ...]) -> list[FileSummary]:
    root = REPO_ROOT / root_glob
    if not root.exists():
        return []
    entries: list[FileSummary] = []
    for file_path in sorted(root.rglob("*")):
        if not file_path.is_file():
            continue
        if file_path.suffix.lower() not in suffixes:
            continue
        if _should_skip(file_path):
            continue
        rel = file_path.relative_to(REPO_ROOT).as_posix()
        entries.append(FileSummary(rel_path=rel, summary=extract_summary(file_path)))
    return entries


def render() -> str:
    out: list[str] = [PREAMBLE]
    for header, root_glob, suffixes in SECTIONS:
        entries = collect_section(root_glob, suffixes)
        if not entries:
            continue
        out.append(f"## {header}\n")
        for entry in entries:
            if entry.summary:
                out.append(f"- `{entry.rel_path}` — {entry.summary}")
            else:
                out.append(f"- `{entry.rel_path}` — _(no docstring)_")
        out.append("")  # blank line between sections
    # Trailing footer with regen reminder.
    out.append("---")
    out.append(
        "_Regenerate: `python scripts/regenerate_index.py`. "
        "A missing description means the file lacks a header docstring."
    )
    return "\n".join(out) + "\n"


# ─────────────────────────────────────────────────────────────────────
# Entry point
# ─────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate INDEX.md.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if INDEX.md is out of date (CI / pre-commit guard).",
    )
    parser.add_argument(
        "--stdout",
        action="store_true",
        help="Print to stdout instead of writing INDEX.md.",
    )
    args = parser.parse_args(argv)

    rendered = render()
    if args.stdout:
        sys.stdout.write(rendered)
        return 0

    existing = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.exists() else ""
    if args.check:
        if existing != rendered:
            print(
                f"INDEX.md is stale. Run: python {Path(__file__).relative_to(REPO_ROOT)}",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    files_indexed = sum(
        1
        for _h, root, suf in SECTIONS
        for _e in collect_section(root, suf)
    )
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({files_indexed} files indexed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


# ─────────────────────────────────────────────────────────────────────
# Optional: wire as a git pre-commit hook
# ─────────────────────────────────────────────────────────────────────
# Save the following to .git/hooks/pre-commit (chmod +x):
#
#   #!/usr/bin/env bash
#   set -e
#   python scripts/regenerate_index.py
#   git add INDEX.md
#
# That regenerates INDEX.md on every commit + stages it so the index
# stays current without anyone having to remember.
