import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Video 02 — BrewSLM Quickstart, narrated take.
//
// Mirrors 02-brewslm-quickstart.spec.ts but paces each section to
// match the duration of its narration WAV (generated by
// tts/generate_narration.py and saved under tts/audio/). The final
// video gets muxed against the concatenated narration audio so the
// on-screen action lines up with the spoken text.
//
// Audio durations are loaded from tts/audio/v02-durations.json — the
// orchestrator regenerates it whenever narration changes.

const DURATIONS_PATH = path.resolve(
    __dirname,
    '../../tts/audio/v02-durations.json',
);

type Durations = {
    cold_open: number;
    login: number;
    tiles: number;
    seed: number;
    cleaning: number;
    goldset: number;
    dataprep: number;
    training: number;
    expand_wrap: number;
};

const dur: Durations = JSON.parse(fs.readFileSync(DURATIONS_PATH, 'utf-8'));

const SCREENSHOT_DIR = 'docs-demo/screenshots';

// Pad a section so its wall-clock matches the audio length. Returns
// the milliseconds to sleep after the action work is done. The pad
// must be non-negative; if the action took longer than the audio, we
// simply do not pad (the audio drifts a tiny bit but never cuts off
// mid-action).
async function padTo(
    page: import('@playwright/test').Page,
    sectionStartMs: number,
    sectionDurationSeconds: number,
) {
    const targetMs = sectionDurationSeconds * 1000;
    const elapsedMs = Date.now() - sectionStartMs;
    const remaining = targetMs - elapsedMs;
    if (remaining > 0) {
        await page.waitForTimeout(remaining);
    }
}

// Scroll the named element into the viewport center so the recorded
// 1440x900 video actually shows what the narration is about.
async function focusOn(
    page: import('@playwright/test').Page,
    selector: string,
) {
    const el = page.locator(selector).first();
    if ((await el.count()) > 0) {
        await el.evaluate((node) =>
            node.scrollIntoView({ block: 'center', behavior: 'instant' as ScrollBehavior }),
        );
        await page.waitForTimeout(300);
    }
}

test('Video 02 — narrated take', async ({ page }) => {
    test.setTimeout(8 * 60_000); // total audio ≈ 3m46s + slack

    // ── Section: cold open (no action; just hold the login page) ─────
    let sectionStart = Date.now();
    await page.goto('/login');
    await expect(page.getByPlaceholder('Enter your username')).toBeVisible();
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v02n-login.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cold_open);

    // ── Section: login ───────────────────────────────────────────────
    sectionStart = Date.now();
    await page.getByPlaceholder('Enter your username').fill('admin');
    await page.getByPlaceholder('API Key or Password').fill('sk-mock-admin-key');
    await page.getByRole('button', { name: /^Sign in$/ }).click();
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 });
    await padTo(page, sectionStart, dur.login);

    // ── Section: tiles ───────────────────────────────────────────────
    sectionStart = Date.now();
    await expect(page.locator('.demo-project-tiles')).toBeVisible();
    await focusOn(page, '.demo-project-tiles');
    const supportFaqTile = page.locator(
        '[aria-label="Open the Demo · Support FAQ demo project"]',
    );
    await expect(supportFaqTile).toBeVisible();
    await supportFaqTile.hover();
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v02n-tiles.png`, fullPage: true });
    await padTo(page, sectionStart, dur.tiles);

    // ── Section: seed support-faq + land on Data tab ─────────────────
    sectionStart = Date.now();
    await supportFaqTile.click();
    await page.waitForURL(/\/project\/\d+\/pipeline\/data/, { timeout: 30_000 });
    await expect(page.locator('button.tab[title="Data"]')).toBeVisible();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v02n-data-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.seed);

    // ── Section: cleaning ────────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Cleaning"]').click();
    await page.waitForTimeout(800);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v02n-cleaning-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cleaning);

    // ── Section: gold set (viewport-only screenshot) ─────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Gold Set"]').click();
    await page.waitForTimeout(800);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v02n-goldset-tab.png`, fullPage: false });
    await padTo(page, sectionStart, dur.goldset);

    // ── Section: dataset prep ────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Dataset Prep"]').click();
    await page.waitForTimeout(800);
    await focusOn(page, '.tab-content');
    await padTo(page, sectionStart, dur.dataprep);

    // ── Section: training (empty state) ──────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Training"]').click();
    await page.waitForTimeout(800);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v02n-training-tab-empty.png`, fullPage: true });
    await padTo(page, sectionStart, dur.training);

    // ── Section: expand raw row + wrap ───────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Data"]').click();
    await page.waitForTimeout(800);
    const firstExpander = page.locator('[data-testid^="expand-doc-"]').first();
    await expect(firstExpander).toBeVisible();
    await focusOn(page, '[data-testid^="expand-doc-"]');
    await firstExpander.click();
    await page.waitForTimeout(1500);
    // The expanded row is rendered just below the row that was clicked;
    // re-focus so the {question, answer} payload is centered.
    await focusOn(page, '[data-testid^="expand-doc-"]');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v02n-expanded-row.png`, fullPage: true });
    await padTo(page, sectionStart, dur.expand_wrap);
});
