import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Video 03 — Support FAQ Pipeline, narrated walkthrough.
//
// Walks the seeded support-faq project across the 10 pipeline tabs
// plus the dedicated Training Config page. No runtime-heavy actions
// (no synthetic generation, no training launch, no tokenizer
// analysis). Audio durations come from tts/audio/v03-durations.json
// (generated by tts/generate_v03_narration.py).

const DURATIONS_PATH = path.resolve(
    __dirname,
    '../../tts/audio/v03-durations.json',
);

type Durations = {
    cold_open: number;
    data: number;
    cleaning: number;
    goldset: number;
    synthetic: number;
    dataprep: number;
    tokenization: number;
    training_config: number;
    eval_wrap: number;
};

const dur: Durations = JSON.parse(fs.readFileSync(DURATIONS_PATH, 'utf-8'));

const SCREENSHOT_DIR = 'docs-demo/screenshots';

async function padTo(
    page: import('@playwright/test').Page,
    sectionStartMs: number,
    sectionDurationSeconds: number,
) {
    const remaining = sectionDurationSeconds * 1000 - (Date.now() - sectionStartMs);
    if (remaining > 0) await page.waitForTimeout(remaining);
}

// Scroll the named element into the viewport center so the recorded
// 1440x900 video shows what the narration is about.
async function focusOn(
    page: import('@playwright/test').Page,
    selector: string,
) {
    const el = page.locator(selector).first();
    if ((await el.count()) > 0) {
        await el.evaluate((node) =>
            node.scrollIntoView({ block: 'center', behavior: 'instant' as ScrollBehavior }),
        );
        await page.waitForTimeout(300);
    }
}

test('Video 03 — Support FAQ pipeline narrated', async ({ page }) => {
    test.setTimeout(10 * 60_000);

    // Pre-step: log in and seed support-faq. Not narrated — Video 02
    // already covered the seed flow. Video 03 picks up on the Data tab.
    await page.goto('/login');
    await page.getByPlaceholder('Enter your username').fill('admin');
    await page.getByPlaceholder('API Key or Password').fill('sk-mock-admin-key');
    await page.getByRole('button', { name: /^Sign in$/ }).click();
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 });
    await page
        .locator('[aria-label="Open the Demo · Support FAQ demo project"]')
        .click();
    await page.waitForURL(/\/project\/\d+\/pipeline\/data/, { timeout: 30_000 });
    await expect(page.locator('button.tab[title="Data"]')).toBeVisible();

    // Capture the project URL so we can deep-link back to /pipeline/eval
    // after the training-config detour.
    const projectUrlMatch = page.url().match(/\/project\/(\d+)\//);
    const projectId = projectUrlMatch ? projectUrlMatch[1] : '';
    expect(projectId).not.toBe('');

    // ── Section: cold open (on Data tab) ─────────────────────────────
    let sectionStart = Date.now();
    await page.waitForTimeout(1000); // give the page a moment to settle
    await focusOn(page, '.tab-content');
    await padTo(page, sectionStart, dur.cold_open);

    // ── Section: data tab + expand a raw row ─────────────────────────
    sectionStart = Date.now();
    const firstExpander = page.locator('[data-testid^="expand-doc-"]').first();
    await expect(firstExpander).toBeVisible();
    await focusOn(page, '[data-testid^="expand-doc-"]');
    await firstExpander.click();
    await page.waitForTimeout(2000);
    await focusOn(page, '[data-testid^="expand-doc-"]');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-data-expanded.png`, fullPage: true });
    await padTo(page, sectionStart, dur.data);

    // ── Section: cleaning ────────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Cleaning"]').click();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-cleaning-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cleaning);

    // ── Section: gold set ────────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Gold Set"]').click();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-goldset-tab.png`, fullPage: false });
    await padTo(page, sectionStart, dur.goldset);

    // ── Section: synthetic ───────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Synthetic"]').click();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-synthetic-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.synthetic);

    // ── Section: dataset prep ────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Dataset Prep"]').click();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-dataprep-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.dataprep);

    // ── Section: tokenization ────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Tokenization"]').click();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-tokenization-tab.png`, fullPage: false });
    await padTo(page, sectionStart, dur.tokenization);

    // ── Section: training tab → training config (Essentials/Advanced)
    sectionStart = Date.now();
    await page.locator('button.tab[title="Training"]').click();
    await page.waitForTimeout(1200);
    await page.getByRole('button', { name: /Open Training Config/ }).click();
    await page.waitForURL(/\/project\/\d+\/training-config/, { timeout: 15_000 });
    await page.waitForTimeout(1500);
    // Default is Essentials; capture, then flip to Advanced.
    await focusOn(page, 'button[role="tab"]:has-text("Essentials")');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-training-config-essentials.png`, fullPage: false });
    await page.getByRole('tab', { name: 'Advanced' }).click();
    await page.waitForTimeout(1500);
    await focusOn(page, 'button[role="tab"]:has-text("Advanced")');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-training-config-advanced.png`, fullPage: false });
    await padTo(page, sectionStart, dur.training_config);

    // ── Section: eval tab + wrap ─────────────────────────────────────
    sectionStart = Date.now();
    await page.goto(`/project/${projectId}/pipeline/eval`);
    await expect(page.locator('button.tab[title="Evaluation"]')).toBeVisible();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v03-eval-tab.png`, fullPage: false });
    await padTo(page, sectionStart, dur.eval_wrap);
});
