import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Video 04 — PII Detector Pipeline, narrated walkthrough.
//
// Walks the seeded pii-detector project across all 10 pipeline tabs
// plus the Training Config page. Same shape as Video 03 (no
// synthetic generation, no training launch), but with a different
// sample and the Section 3 (Cleaning) disambiguation between
// cleaning-time PII redaction and the PII Detector model task.
//
// Durations come from tts/audio/v04-durations.json (generated by
// tts/generate_v04_narration.py).

const DURATIONS_PATH = path.resolve(
    __dirname,
    '../../tts/audio/v04-durations.json',
);

type Durations = {
    cold_open: number;
    data: number;
    cleaning: number;
    goldset: number;
    synthetic: number;
    dataprep: number;
    tokenization: number;
    training_config: number;
    eval_wrap: number;
};

const dur: Durations = JSON.parse(fs.readFileSync(DURATIONS_PATH, 'utf-8'));

const SCREENSHOT_DIR = 'docs-demo/screenshots';

async function padTo(
    page: import('@playwright/test').Page,
    sectionStartMs: number,
    sectionDurationSeconds: number,
) {
    const remaining = sectionDurationSeconds * 1000 - (Date.now() - sectionStartMs);
    if (remaining > 0) await page.waitForTimeout(remaining);
}

test('Video 04 — PII Detector pipeline narrated', async ({ page }) => {
    test.setTimeout(10 * 60_000);

    // Pre-roll: log in, seed pii-detector, land on Data tab.
    await page.goto('/login');
    await page.getByPlaceholder('Enter your username').fill('admin');
    await page.getByPlaceholder('API Key or Password').fill('sk-mock-admin-key');
    await page.getByRole('button', { name: /^Sign in$/ }).click();
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 });
    await page
        .locator('[aria-label="Open the Demo · PII / PCI Detector demo project"]')
        .click();
    await page.waitForURL(/\/project\/\d+\/pipeline\/data/, { timeout: 30_000 });
    await expect(page.locator('button.tab[title="Data"]')).toBeVisible();

    const projectId = (page.url().match(/\/project\/(\d+)\//) || [])[1] ?? '';
    expect(projectId).not.toBe('');

    // ── Section: cold open (on Data tab) ─────────────────────────────
    let sectionStart = Date.now();
    await page.waitForTimeout(1000);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v04-data-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cold_open);

    // ── Section: data tab + expand a row ─────────────────────────────
    sectionStart = Date.now();
    const firstExpander = page.locator('[data-testid^="expand-doc-"]').first();
    await expect(firstExpander).toBeVisible();
    await firstExpander.click();
    await page.waitForTimeout(2000);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v04-expanded-row.png`, fullPage: true });
    await padTo(page, sectionStart, dur.data);

    // ── Section: cleaning (the disambiguation beat) ──────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Cleaning"]').click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v04-cleaning-redact.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cleaning);

    // ── Section: gold set ────────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Gold Set"]').click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v04-goldset.png`, fullPage: false });
    await padTo(page, sectionStart, dur.goldset);

    // ── Section: synthetic (span mode auto-selected from manifest) ──
    sectionStart = Date.now();
    await page.locator('button.tab[title="Synthetic"]').click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v04-synthetic-span.png`, fullPage: true });
    await padTo(page, sectionStart, dur.synthetic);

    // ── Section: dataset prep (schema profile shows span_set) ───────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Dataset Prep"]').click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v04-schema-profile.png`, fullPage: true });
    await padTo(page, sectionStart, dur.dataprep);

    // ── Section: tokenization ────────────────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Tokenization"]').click();
    await page.waitForTimeout(1500);
    await padTo(page, sectionStart, dur.tokenization);

    // ── Section: training → training config (Essentials → Advanced) ─
    sectionStart = Date.now();
    await page.locator('button.tab[title="Training"]').click();
    await page.waitForTimeout(1200);
    await page.getByRole('button', { name: /Open Training Config/ }).click();
    await page.waitForURL(/\/project\/\d+\/training-config/, { timeout: 15_000 });
    await page.waitForTimeout(1500);
    await page.getByRole('tab', { name: 'Advanced' }).click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v04-training-power-tools.png`, fullPage: false });
    await padTo(page, sectionStart, dur.training_config);

    // ── Section: eval + wrap ─────────────────────────────────────────
    sectionStart = Date.now();
    await page.goto(`/project/${projectId}/pipeline/eval`);
    await expect(page.locator('button.tab[title="Evaluation"]')).toBeVisible();
    await page.waitForTimeout(1500);
    await padTo(page, sectionStart, dur.eval_wrap);
});
