import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Video 05 — Sentiment Classifier Pipeline, narrated walkthrough.
//
// Walks the seeded sentiment-classifier project across the relevant
// pipeline tabs. Skips Cleaning + Synthetic as their own sections
// (those got their own treatment in Videos 03 and 04) and adds
// Compression + Export — surfaces that are particularly relevant for
// this sample's mobile_cpu target.
//
// Durations come from tts/audio/v05-durations.json (generated by
// tts/generate_v05_narration.py).

const DURATIONS_PATH = path.resolve(
    __dirname,
    '../../tts/audio/v05-durations.json',
);

type Durations = {
    cold_open: number;
    data: number;
    goldset: number;
    dataprep: number;
    tokenization: number;
    training_config: number;
    eval: number;
    compression_export: number;
    wrap: number;
};

const dur: Durations = JSON.parse(fs.readFileSync(DURATIONS_PATH, 'utf-8'));

const SCREENSHOT_DIR = 'docs-demo/screenshots';

async function padTo(
    page: import('@playwright/test').Page,
    sectionStartMs: number,
    sectionDurationSeconds: number,
) {
    const remaining = sectionDurationSeconds * 1000 - (Date.now() - sectionStartMs);
    if (remaining > 0) await page.waitForTimeout(remaining);
}

test('Video 05 — Sentiment Classifier pipeline narrated', async ({ page }) => {
    test.setTimeout(10 * 60_000);

    // Pre-roll: log in, seed sentiment-classifier, land on Data tab.
    await page.goto('/login');
    await page.getByPlaceholder('Enter your username').fill('admin');
    await page.getByPlaceholder('API Key or Password').fill('sk-mock-admin-key');
    await page.getByRole('button', { name: /^Sign in$/ }).click();
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 });
    await page
        .locator('[aria-label="Open the Demo · Sentiment classifier demo project"]')
        .click();
    await page.waitForURL(/\/project\/\d+\/pipeline\/data/, { timeout: 30_000 });
    await expect(page.locator('button.tab[title="Data"]')).toBeVisible();

    const projectId = (page.url().match(/\/project\/(\d+)\//) || [])[1] ?? '';
    expect(projectId).not.toBe('');

    // ── Section: cold open (on Data tab) ─────────────────────────────
    let sectionStart = Date.now();
    await page.waitForTimeout(1000);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v05-data-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cold_open);

    // ── Section: data tab + expand a row ─────────────────────────────
    sectionStart = Date.now();
    const firstExpander = page.locator('[data-testid^="expand-doc-"]').first();
    await expect(firstExpander).toBeVisible();
    await firstExpander.click();
    await page.waitForTimeout(2000);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v05-expanded-row.png`, fullPage: true });
    await padTo(page, sectionStart, dur.data);

    // ── Section: gold set (with distribution callout) ────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Gold Set"]').click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v05-goldset.png`, fullPage: false });
    await padTo(page, sectionStart, dur.goldset);

    // ── Section: dataset prep (labels) ───────────────────────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Dataset Prep"]').click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v05-schema-profile.png`, fullPage: true });
    await padTo(page, sectionStart, dur.dataprep);

    // ── Section: tokenization (mobile sequence-length angle) ─────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Tokenization"]').click();
    await page.waitForTimeout(1500);
    await padTo(page, sectionStart, dur.tokenization);

    // ── Section: training → training config (Advanced) ──────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Training"]').click();
    await page.waitForTimeout(1200);
    await page.getByRole('button', { name: /Open Training Config/ }).click();
    await page.waitForURL(/\/project\/\d+\/training-config/, { timeout: 15_000 });
    await page.waitForTimeout(1500);
    await page.getByRole('tab', { name: 'Advanced' }).click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v05-training-config-mobile.png`, fullPage: false });
    await padTo(page, sectionStart, dur.training_config);

    // ── Section: eval (classification pack callout) ──────────────────
    sectionStart = Date.now();
    await page.goto(`/project/${projectId}/pipeline/eval`);
    await expect(page.locator('button.tab[title="Evaluation"]')).toBeVisible();
    await page.waitForTimeout(1500);
    await padTo(page, sectionStart, dur.eval);

    // ── Section: compression + export (ONNX-INT8 future) ────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Compression"]').click();
    await page.waitForTimeout(1500);
    await page.locator('button.tab[title="Export"]').click();
    await page.waitForTimeout(1500);
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v05-export-onnx.png`, fullPage: true });
    await padTo(page, sectionStart, dur.compression_export);

    // ── Section: wrap (hold on the export tab) ───────────────────────
    sectionStart = Date.now();
    await padTo(page, sectionStart, dur.wrap);
});
