import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Video 09 — Training Run, narrated.
//
// First runtime-dependent video in the series. Drives an actual
// training experiment on the support-faq sample (SmolLM2-135M, 2
// epochs, 16 steps, ~12s wall time on GB10) using the real Celery
// worker via builtin.external_celery runtime.
//
// The experiment create+start sequence happens via the backend API
// (page.request.post with the JWT from local login) — not by typing
// into the UI form — so the recording stays deterministic. The
// Training tab UI then displays the running and completed states
// because of its built-in polling.
//
// Durations come from tts/audio/v09-durations.json
// (generated by tts/generate_v09_narration.py).

const DURATIONS_PATH = path.resolve(
    __dirname,
    '../../tts/audio/v09-durations.json',
);

type Durations = {
    cold_open: number;
    config_recap: number;
    kickoff: number;
    watching: number;
    results: number;
    wrap: number;
};

const dur: Durations = JSON.parse(fs.readFileSync(DURATIONS_PATH, 'utf-8'));

const SCREENSHOT_DIR = 'docs-demo/screenshots';

async function padTo(
    page: import('@playwright/test').Page,
    sectionStartMs: number,
    sectionDurationSeconds: number,
) {
    const remaining = sectionDurationSeconds * 1000 - (Date.now() - sectionStartMs);
    if (remaining > 0) await page.waitForTimeout(remaining);
}

// Playwright records video at the viewport size (1440x900). Without
// scrolling, anything below the fold is invisible to the viewer even
// though screenshot({fullPage: true}) captures it. Call this whenever
// the narration is about to talk about a specific element.
async function focusOn(
    page: import('@playwright/test').Page,
    selector: string,
) {
    const el = page.locator(selector).first();
    if ((await el.count()) > 0) {
        await el.evaluate((node) =>
            node.scrollIntoView({ block: 'center', behavior: 'instant' as ScrollBehavior }),
        );
        await page.waitForTimeout(300);
    }
}

test('Video 09 — Training Run narrated', async ({ page, request }) => {
    test.setTimeout(10 * 60_000);

    // ── Pre-roll (not narrated) ──────────────────────────────────────
    // Acquire JWT via the same local login the UI uses. Used for the
    // API-side experiment create + start later.
    const loginResp = await request.post('http://localhost:8000/api/auth/local/login', {
        data: { username: 'admin', password: 'sk-mock-admin-key' },
    });
    expect(loginResp.ok()).toBeTruthy();
    const token = (await loginResp.json()).token as string;
    const authHeader = { Authorization: `Bearer ${token}` };

    // UI login
    await page.goto('/login');
    await page.getByPlaceholder('Enter your username').fill('admin');
    await page.getByPlaceholder('API Key or Password').fill('sk-mock-admin-key');
    await page.getByRole('button', { name: /^Sign in$/ }).click();
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 });

    // Open support-faq + land on Data tab
    await page
        .locator('[aria-label="Open the Demo · Support FAQ demo project"]')
        .click();
    await page.waitForURL(/\/project\/\d+\/pipeline\/data/, { timeout: 30_000 });

    const projectId = (page.url().match(/\/project\/(\d+)\//) || [])[1] ?? '';
    expect(projectId).not.toBe('');

    // Navigate to the Training tab — section starting point.
    await page.locator('button.tab[title="Training"]').click();
    await page.waitForTimeout(1500);
    // Bring the Training Runs section into view — that's the table the
    // narration is about.
    await focusOn(page, '.tab-content');

    // ── Section: cold open (Training tab empty state) ────────────────
    let sectionStart = Date.now();
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v09-training-tab-empty.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cold_open);

    // ── Section: config recap (Essentials → Advanced) ────────────────
    // Audio breakdown (~17.5s): ~1.5s intro, ~5s on Essentials
    // (base model, epochs, batch size, LR), ~7s on Advanced (LoRA
    // rank, target modules, optimizer), ~2s closing.
    //
    // The training-config page has TWO levels of tabs:
    //   1. Mode toggle (top right): Essentials | Advanced
    //   2. Setup sub-tabs (mid-page): Basics | Config | Power Tools | Review
    //
    // The form fields the narration names live in the SUB-TABS,
    // not on the default landing view:
    //   - "Base Model" / "Epochs" / "Batch Size" / "LR" live in Config
    //   - "Advanced & PEFT" (LoRA / target modules / optimizer)
    //     lives in Power Tools, which only renders in Advanced mode.
    sectionStart = Date.now();
    await page.getByRole('button', { name: /Open Training Config/ }).click();
    await page.waitForURL(/\/project\/\d+\/training-config/, { timeout: 15_000 });
    await page.waitForTimeout(1500);

    // First half — Essentials. Click the Config sub-tab so Base
    // Model / Epochs / Batch Size / LR are actually rendered, then
    // scroll the form into view.
    await page.locator('button.training-setup-tab:has-text("Config")').click();
    await page.waitForTimeout(600);
    await focusOn(page, 'label.form-label:has-text("Base Model")');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v09-config-essentials.png`, fullPage: false });
    // Hold on Essentials/Config for ~45% of the section (covers the
    // "Essentials view covers base model, epochs..." beat).
    const essentialsHoldMs =
        dur.config_recap * 1000 * 0.45 - (Date.now() - sectionStart);
    if (essentialsHoldMs > 0) await page.waitForTimeout(essentialsHoldMs);

    // Second half — Advanced. Flip the mode toggle (top-right) which
    // unlocks the Power Tools sub-tab, then click into Power Tools
    // and scroll to the "Advanced & PEFT" heading. That puts the
    // LoRA / target-modules / optimizer fields on screen while
    // narration names them.
    await page.getByRole('tab', { name: 'Advanced' }).click();
    await page.waitForTimeout(800);
    await page.locator('button.training-setup-tab:has-text("Power Tools")').click();
    await page.waitForTimeout(600);
    await focusOn(page, 'h4.training-config-section-title:has-text("Advanced & PEFT")');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v09-config-advanced.png`, fullPage: false });
    await padTo(page, sectionStart, dur.config_recap);

    // ── Section: kickoff — back to Training tab + API start ─────────
    sectionStart = Date.now();
    await page.goto(`/project/${projectId}/pipeline/training`);
    await page.waitForTimeout(800);
    await focusOn(page, '.tab-content');

    // Create the experiment via API. Overrides:
    // - SmolLM2-135M-Instruct: small, ungated, instruction-tuned.
    // - 2 epochs / batch 2 / no packing: keeps it ~12s on GB10.
    // - adamw_torch instead of paged_adamw_8bit: avoids bitsandbytes
    //   dependency on aarch64.
    const createResp = await request.post(
        `http://localhost:8000/api/projects/${projectId}/training/experiments`,
        {
            headers: authHeader,
            data: {
                name: 'v09-narrated-run',
                description: 'Video 09 narrated training run on support-faq.',
                config: {
                    base_model: 'HuggingFaceTB/SmolLM2-135M-Instruct',
                    num_epochs: 2,
                    batch_size: 2,
                    gradient_accumulation_steps: 1,
                    optimizer: 'adamw_torch',
                    max_seq_length: 512,
                    sequence_packing: false,
                    warmup_ratio: 0.0,
                },
            },
        },
    );
    expect(createResp.ok()).toBeTruthy();
    const expId = (await createResp.json()).id as number;

    // Start the experiment
    const startResp = await request.post(
        `http://localhost:8000/api/projects/${projectId}/training/experiments/${expId}/start`,
        { headers: authHeader, data: {} },
    );
    expect(startResp.ok()).toBeTruthy();

    // Refresh the UI so the new experiment row shows up
    await page.reload();
    await page.waitForTimeout(1500);
    // Scroll the runs list into view — that's where the new experiment
    // appears.
    await focusOn(page, '.training-experiment-item');
    await padTo(page, sectionStart, dur.kickoff);

    // ── Section: watching — wait for completion (status polling) ────
    sectionStart = Date.now();
    await focusOn(page, '.training-experiment-item');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v09-training-running.png`, fullPage: true });

    // Poll until the API reports completed (or training section audio
    // ends, whichever is later — padTo handles the timing).
    const deadlineMs = sectionStart + dur.watching * 1000 + 30_000; // 30s slack
    let finalStatus = 'unknown';
    while (Date.now() < deadlineMs) {
        const statusResp = await request.get(
            `http://localhost:8000/api/projects/${projectId}/training/experiments/${expId}/status`,
            { headers: authHeader },
        );
        if (statusResp.ok()) {
            const s = (await statusResp.json()).status as string;
            finalStatus = s;
            if (['completed', 'failed', 'cancelled'].includes(s)) break;
        }
        await page.waitForTimeout(2000);
    }
    expect(finalStatus).toBe('completed');

    // Refresh once more to land the completed status in the UI
    await page.reload();
    await page.waitForTimeout(1500);
    await focusOn(page, '.training-experiment-item');
    await padTo(page, sectionStart, dur.watching);

    // ── Section: results (completed state with metrics) ──────────────
    sectionStart = Date.now();
    await focusOn(page, '.training-experiment-item');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v09-training-completed.png`, fullPage: true });
    await padTo(page, sectionStart, dur.results);

    // ── Section: wrap ────────────────────────────────────────────────
    sectionStart = Date.now();
    await padTo(page, sectionStart, dur.wrap);
});
