import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

// Video 11 — Compression + Export, narrated.
//
// Third runtime-dependent video. Takes the LoRA adapter from V09's
// trained experiment, merges it into SmolLM2-135M base, quantizes
// the merged weights to GGUF Q4_K_M via llama.cpp, then registers
// the artifact through the Export pipeline.
//
// Wall-time budget:
//   - merge_lora API call → ~12s on GB10
//   - quantize API call → ~5s
//   - export create + run → ~3s
//
// Durations come from tts/audio/v11-durations.json (generated by
// tts/generate_v11_narration.py).

const DURATIONS_PATH = path.resolve(
    __dirname,
    '../../tts/audio/v11-durations.json',
);

type Durations = {
    cold_open: number;
    compression_setup: number;
    compress_run: number;
    compression_result: number;
    export_create: number;
    export_run: number;
    wrap: number;
};

const dur: Durations = JSON.parse(fs.readFileSync(DURATIONS_PATH, 'utf-8'));

const SCREENSHOT_DIR = 'docs-demo/screenshots';

async function padTo(
    page: import('@playwright/test').Page,
    sectionStartMs: number,
    sectionDurationSeconds: number,
) {
    const remaining = sectionDurationSeconds * 1000 - (Date.now() - sectionStartMs);
    if (remaining > 0) await page.waitForTimeout(remaining);
}

async function focusOn(
    page: import('@playwright/test').Page,
    selector: string,
) {
    const el = page.locator(selector).first();
    if ((await el.count()) > 0) {
        await el.evaluate((node) =>
            node.scrollIntoView({ block: 'center', behavior: 'instant' as ScrollBehavior }),
        );
        await page.waitForTimeout(300);
    }
}

test('Video 11 — Compression + Export narrated', async ({ page, request }) => {
    test.setTimeout(15 * 60_000);

    // Pre-roll: log in + acquire JWT
    const loginResp = await request.post('http://localhost:8000/api/auth/local/login', {
        data: { username: 'admin', password: 'sk-mock-admin-key' },
    });
    expect(loginResp.ok()).toBeTruthy();
    const token = (await loginResp.json()).token as string;
    const authHeader = { Authorization: `Bearer ${token}` };

    await page.goto('/login');
    await page.getByPlaceholder('Enter your username').fill('admin');
    await page.getByPlaceholder('API Key or Password').fill('sk-mock-admin-key');
    await page.getByRole('button', { name: /^Sign in$/ }).click();
    await page.waitForURL((url) => url.pathname === '/', { timeout: 15_000 });

    await page
        .locator('[aria-label="Open the Demo · Support FAQ demo project"]')
        .click();
    await page.waitForURL(/\/project\/\d+\/pipeline\/data/, { timeout: 30_000 });
    const projectId = (page.url().match(/\/project\/(\d+)\//) || [])[1] ?? '';
    expect(projectId).not.toBe('');

    // Assert V09's experiment exists and is completed
    const expsResp = await request.get(
        `http://localhost:8000/api/projects/${projectId}/training/experiments`,
        { headers: authHeader },
    );
    const exps = (await expsResp.json()) as Array<{
        id: number;
        name: string;
        status: string;
        output_dir: string;
    }>;
    const v09 = exps.find((e) => e.name === 'v09-narrated-run' && e.status === 'completed');
    expect(v09, 'V09 experiment required; run 09-training-run-narrated.spec.ts first').toBeTruthy();
    const experimentId = (v09 as { id: number }).id;
    const adapterPath = (v09 as { output_dir: string }).output_dir + '/model';

    // Navigate to the Compression tab — section starting point.
    await page.locator('button.tab[title="Compression"]').click();
    await page.waitForTimeout(1500);
    await focusOn(page, '.tab-content');

    // ── Section: cold open ───────────────────────────────────────────
    let sectionStart = Date.now();
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v11-compression-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.cold_open);

    // ── Section: compression setup ───────────────────────────────────
    // Fill in the form so the viewer sees the actual fields the
    // narration is naming. The Compression panel uses no testids;
    // selectors are label-driven.
    sectionStart = Date.now();
    await page.locator('input.input').first().fill('HuggingFaceTB/SmolLM2-135M-Instruct');
    await page.waitForTimeout(300);
    // Bits dropdown — already defaults to 4-bit but interact to make
    // the form feel "set up" in the recording.
    await focusOn(page, ':text("Quantization Bits")');
    // LoRA adapter path — third input in the form.
    const loraInput = page.locator('label:has-text("LoRA Adapter Path") + input.input').first();
    if ((await loraInput.count()) > 0) {
        await loraInput.fill(adapterPath);
    }
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v11-compression-form.png`, fullPage: true });
    await padTo(page, sectionStart, dur.compression_setup);

    // ── Section: compress run (fire merge + quantize via API) ───────
    // The UI is too form-heavy to drive end-to-end reliably; use the
    // API for the create + start sequence, then surface the result
    // visually via the Compression Logs / Result cards.
    sectionStart = Date.now();

    // Step 1: merge LoRA (~12s)
    const mergeResp = await request.post(
        `http://localhost:8000/api/projects/${projectId}/compression/merge-lora`,
        {
            headers: authHeader,
            data: {
                base_model_path: 'HuggingFaceTB/SmolLM2-135M-Instruct',
                lora_adapter_path: adapterPath,
            },
        },
    );
    expect(mergeResp.ok()).toBeTruthy();
    const mergeJob = await mergeResp.json();
    const mergeTaskId = mergeJob.task_id as string;

    // Poll merge to completion
    const mergeDeadline = Date.now() + 60_000;
    while (Date.now() < mergeDeadline) {
        const r = await request.get(
            `http://localhost:8000/api/projects/${projectId}/compression/jobs/tasks/${mergeTaskId}`,
            { headers: authHeader },
        );
        if (r.ok()) {
            const s = (await r.json()).state as string;
            if (s.toLowerCase() === 'success' || s.toLowerCase() === 'failure') break;
        }
        await page.waitForTimeout(2000);
    }

    // Step 2: quantize (~5s)
    const mergedModelDir = mergeJob.output_model_path as string;
    const quantResp = await request.post(
        `http://localhost:8000/api/projects/${projectId}/compression/quantize`,
        {
            headers: authHeader,
            data: {
                model_path: mergedModelDir,
                bits: 4,
                output_format: 'gguf',
            },
        },
    );
    expect(quantResp.ok()).toBeTruthy();
    const quantJob = await quantResp.json();
    const quantTaskId = quantJob.task_id as string;

    const quantDeadline = Date.now() + 60_000;
    while (Date.now() < quantDeadline) {
        const r = await request.get(
            `http://localhost:8000/api/projects/${projectId}/compression/jobs/tasks/${quantTaskId}`,
            { headers: authHeader },
        );
        if (r.ok()) {
            const s = (await r.json()).state as string;
            if (s.toLowerCase() === 'success' || s.toLowerCase() === 'failure') break;
        }
        await page.waitForTimeout(2000);
    }
    await padTo(page, sectionStart, dur.compress_run);

    // ── Section: compression result ──────────────────────────────────
    // The UI's Compression Logs / Result cards only render after a
    // UI-driven action. Since we fired via API, surface the result
    // by reloading the Compression tab — the form state resets but
    // the artifact on disk is visible via "ls" mental model.
    sectionStart = Date.now();
    // Re-render the compression tab (no result panel populated for
    // an API-driven flow, but the viewer's eyes are on the form +
    // narration is doing the heavy lifting here).
    await focusOn(page, '.tab-content');
    await padTo(page, sectionStart, dur.compression_result);

    // ── Section: export create (navigate to Export tab) ─────────────
    sectionStart = Date.now();
    await page.locator('button.tab[title="Export"]').click();
    await page.waitForTimeout(1500);
    await focusOn(page, ':text("Export and Registry")');
    await page.screenshot({ path: `${SCREENSHOT_DIR}/v11-export-tab.png`, fullPage: true });
    await padTo(page, sectionStart, dur.export_create);

    // ── Section: export run ──────────────────────────────────────────
    sectionStart = Date.now();
    // Fire export create + run via API
    const exportCreateResp = await request.post(
        `http://localhost:8000/api/projects/${projectId}/export/create`,
        {
            headers: authHeader,
            data: {
                experiment_id: experimentId,
                export_format: 'gguf',
                quantization: 'Q4_K_M',
            },
        },
    );
    expect(exportCreateResp.ok()).toBeTruthy();
    const exportJob = await exportCreateResp.json();
    const exportId = exportJob.id as number;

    const exportRunResp = await request.post(
        `http://localhost:8000/api/projects/${projectId}/export/${exportId}/run`,
        {
            headers: authHeader,
            data: { run_smoke_tests: false },
        },
    );
    // Run may fail validation if the GGUF isn't placed in the export
    // dir — we accept either outcome here because the recording's
    // value is the on-screen surface, not the export's success state.
    console.log(`[v11] export create id=${exportId} ok=${exportRunResp.ok()}`);
    await page.reload();
    await page.waitForTimeout(1500);
    await page.locator('button.tab[title="Export"]').click();
    await page.waitForTimeout(1000);
    await focusOn(page, '.tab-content');
    await padTo(page, sectionStart, dur.export_run);

    // ── Section: wrap ────────────────────────────────────────────────
    sectionStart = Date.now();
    await padTo(page, sectionStart, dur.wrap);
});
